# Generated by Django 5.1.2 on 2025-01-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_badge_goal_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
