# Generated by Django 5.1.2 on 2025-01-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(to='todo.badge'),
        ),
    ]
