# Generated by Django 5.1.2 on 2025-01-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_userprofile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
